/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.*;

/**
 *
 * @author jaypa
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    JPanel right;
    Personhistory personhistory;
    Encrypt encrypt;
    public CreateJPanel(JPanel right, Personhistory personhistory) {
        initComponents();
        this.right = right;
        this.personhistory = personhistory; 
        this.encrypt = new Encrypt();
    }

  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nidtxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        uidtxt = new javax.swing.JTextField();
        roletxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        nametxt = new javax.swing.JTextField();
        emailtxt = new javax.swing.JTextField();

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        jLabel2.setText("NUID");

        jLabel1.setText("User_ID");

        jLabel5.setText("Role");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Create New Person");

        jButton1.setText("Save Person");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("<<  Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name");

        jLabel8.setText("Email");

        emailtxt.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel5))
                        .addGap(84, 84, 84)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(emailtxt, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                            .addComponent(nametxt)
                            .addComponent(uidtxt)
                            .addComponent(roletxt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(205, 205, 205)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(524, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(nametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(98, 98, 98)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(150, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        right.remove(this);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.previous(right);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(!(uidtxt.getText().chars().allMatch(Character::isDigit))){
                JOptionPane.showMessageDialog(null, "User ID should only be digits!");
                return;
            }
            if(uidtxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter User ID");
                return;
            }
                                
            
//             if(!((emailtxt.getText().contains("@")) && (emailtxt.getText().contains(".")) && emailtxt.getText().equals("")))
//             {
//                 JOptionPane.showMessageDialog(null, "Please enter Correct Email ID");
//                 return;
//             } 
             
//             if(emailtxt.getText().equals(""))
//             {
//                 JOptionPane.showMessageDialog(null, "Please enter Email ID");
//                 return;
//             }
             
          // else if(nametxt.getText().equals(""))
          
            if(nametxt.getText().equals(""))    
           {
                 JOptionPane.showMessageDialog(null, "Please enter First Name");
                 return;
             }
            
//            if(!((emailtxt.getText().contains("@")) && (emailtxt.getText().contains("."))))
//             {
//                return;
//             } 
//            else if (emailtxt.getText().equals(""))
//            {
//                JOptionPane.showMessageDialog(null, "Please enter Correct Email ID");
//            }
             
            if(!isValidEmail(emailtxt.getText()))
             {
                 JOptionPane.showMessageDialog(null, "Please enter Valid Email ID");
                 return;
             }
             if(roletxt.getText().equals(""))
             {
                JOptionPane.showMessageDialog(null, "Please enter Role");

                return;
             }
                

        String userid = uidtxt.getText();
        String nuid = nidtxt.getText();
        String name = nametxt.getText();
        String email = emailtxt.getText();
        String username = unametxt.getText();
        String password = passtxt.getText();
        String role = roletxt.getText();
        
        Person person=personhistory.addPerson();// Adding new person reference
        person.setUserid(userid);
        person.setNuid(nuid);
        person.setName(name);
        person.setEmail(email);
        person.setUsername(username);
        person.setPassword(password);
       //     person.getPasswordlist().add(this.encrypt.encryptPassword(passtxt.getText()));
        person.setRole(role);
        
        
       // System.out.println("Encrypted Password : "+person.getPasswordlist());
        
        JOptionPane.showMessageDialog(this, "Person have been added"); //  showMessageDailog(this, "Vitals have added");
        
        uidtxt.setText("");
        //nidtxt.setText("");
        nametxt.setText("");
        emailtxt.setText("");
        unametxt.setText("");
        passtxt.setText("");
        roletxt.setText("");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private boolean isValidEmail(String email) {
    //        String regex = "^[A-Za-z0-9+_.-]+@(.+)$";
        String regex = "^[A-Za-z0-9+_.-]+@([A-Za-z0-9.-]+)\\.(\\w{2,})$";
        return email.matches(regex);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField emailtxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField nidtxt;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField roletxt;
    private javax.swing.JTextField uidtxt;
    private javax.swing.JTextField unametxt;
    // End of variables declaration//GEN-END:variables
}
