/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.ButtonGroup;
import javax.swing.JOptionPane;
import model.*;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jaypa
 */
public class CuserJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CuserJPanel
     */
    JPanel right;
    Personhistory personhistory;
    Person person;
    Encrypt encrypt;
    public CuserJPanel(JPanel right, Personhistory personhistory, Person person) {
        initComponents();
        this.right = right;
        this.personhistory = personhistory; 
        this.person = person;
        this.encrypt = new Encrypt();
        ButtonGroup enablepro = new ButtonGroup();
        enablepro.add(yesbtn);
        enablepro.add(nobtn);
        populateTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        unametxt = new javax.swing.JTextField();
        passtxt = new javax.swing.JTextField();
        roletxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblvital1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        uidtxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        nuidtxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        yesbtn = new javax.swing.JRadioButton();
        nobtn = new javax.swing.JRadioButton();

        jLabel4.setText("Password");

        jLabel5.setText("Role");

        roletxt.setEditable(false);

        jLabel3.setText("User Name");

        jButton1.setText("Save User");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblvital1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "NUID", "User ID", "Name", "User Name", "Password", "Role", "Enable"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblvital1);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Create User");

        uidtxt.setEditable(false);

        jLabel6.setText("User_ID");

        jButton2.setText("Create User");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("<< Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel2.setText("NUID");

        jLabel7.setText("Enable User?");

        yesbtn.setText("Yes");

        nobtn.setText("No");
        nobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nobtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(305, 305, 305)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(uidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(roletxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(unametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yesbtn)
                                .addGap(31, 31, 31)
                                .addComponent(nobtn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(355, 355, 355)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton3)
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel1)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(uidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nuidtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(passtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(roletxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(yesbtn)
                    .addComponent(nobtn))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(42, 42, 42))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
       int sri = tblvital1.getSelectedRow();
       if (sri < 0)
       {
           JOptionPane.showMessageDialog(this, "Please Select a row to Create");
           return;
       }
      DefaultTableModel model = (DefaultTableModel) tblvital1.getModel();
       Person sv = (Person) model.getValueAt(sri, 0);

       //this.person = person; 
       uidtxt.setText(sv.getUserid());
//       person.setUsername(unametxt.getText());
//       person.setPassword(passtxt.getText());
       roletxt.setText(sv.getRole());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       //this.person = person;
       if(!(nuidtxt.getText().chars().allMatch(Character::isDigit))){
                JOptionPane.showMessageDialog(null, "NU ID should only be digits!");
                return;
            }
            if(nuidtxt.getText().equals("")){
                JOptionPane.showMessageDialog(null, "Please enter NU ID");
                return;
            }
            if(unametxt.getText().equals("")){
                 JOptionPane.showMessageDialog(null, "Please enter Username");
                 return;
             } 
            if((passtxt.getText().equals(""))){
                 JOptionPane.showMessageDialog(null, "Passwords Cannot be null!");
                 return; }

        Person person=(Person)tblvital1.getValueAt(tblvital1.getSelectedRow(), 0);

            for(Person p :personhistory.getPersonlist()){
                if(p.getNuid()==person.getNuid())
                {
                //  person.setUserID( txtUserID.getText());
                // person.setNUID(txtUserNUID.getText());
                 // person.setUsername(txtUserName.getText());
                    person.setNuid(nuidtxt.getText());
                    person.setUsername(unametxt.getText());
                    person.setPassword(passtxt.getText());
                    person.getPasswordlist().add(this.encrypt.encryptPassword(passtxt.getText()));
                    //person.setEnable(true);//To convert person to user
                    System.out.println("Encrypted Password : "+person.getPasswordlist());
                    if (yesbtn.isSelected())
                    {
                        person.setEnable(true);
                    }
                     else
                    {
                        person.setEnable(false);
                    }
                }
            }
       
       JOptionPane.showMessageDialog(this, "User has been created");
       
       

              
              uidtxt.setText("");
              nuidtxt.setText("");
              unametxt.setText("");
              passtxt.setText("");
              roletxt.setText("");
              yesbtn.setSelected(false);
              nobtn.setSelected(false);
             
              populateTabel();

              
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        right.remove(this);
        CardLayout layout = (CardLayout) right.getLayout();
        layout.previous(right);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void nobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nobtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nobtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton nobtn;
    private javax.swing.JTextField nuidtxt;
    private javax.swing.JTextField passtxt;
    private javax.swing.JTextField roletxt;
    private javax.swing.JTable tblvital1;
    private javax.swing.JTextField uidtxt;
    private javax.swing.JTextField unametxt;
    private javax.swing.JRadioButton yesbtn;
    // End of variables declaration//GEN-END:variables
private void populateTabel() 
    {
    
        DefaultTableModel model = (DefaultTableModel) tblvital1.getModel();
        model.setRowCount(0);
        
        for (Person ps : personhistory.getPersonlist())
        {
         Object[] row = new Object[7];
            //row[0] = ps;
//            row[0] = ps.getNuid();
//            row[1] = ps.getUsername();
//            row[2] = ps.getPassword();
//            row[3] = ps.getRole();  
            
             row[0] = ps;
             row [1] = ps.getUserid();
             row[2] = ps.getName();
             row[3] = ps.getUsername();
            row[4] = ps.getPassword();
            row[5] = ps.getRole();
            row[6] = ps.getEnable(); // handle enable functionality
            model.addRow(row);
    }
        
    }

}
